// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package msg

// Injectors from wire.go:

func InitializeMessage(text string) (Message, error) {
	hello := ProvideHello(text)
	return hello, nil
}
