// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package msg

// Injectors from wire.go:

func InitializeHello(text string) (*Hello, error) {
	hello := ProvideHello(text)
	return hello, nil
}
