version: 2 # use CircleCI 2.0
my_workflow:
    jobs:
      - "ApprovalRequest":
          type: approval
      - "Release":
          docker: # run the steps with Docker
            - image: alpine:latest
          steps: 
            - run: echo "Release!"
          requires:
            - "Approval request"
